InternetDialogController: Fix mismatch in argument list after merge of r18.
error:
frameworks/base/packages/SystemUI/src/com/android/systemui/qs/tiles/dialog/InternetDialogController.java:622: error: method connect in class MergedCarrierEntry cannot be applie
d to given types;
            mergedCarrierEntry.connect(null /* ConnectCallback */, false);
                              ^
  required: ConnectCallback
  found: <null>,boolean
  reason: actual and formal argument lists differ in length
1 error

Signed-off-by: spezi77 <spezi7713@gmx.net>